const screens=['chat','case','law','pfa','docs','timeline','attorney','forms','deadlines'];
function view(id){screens.forEach(x=>document.getElementById(x).classList.toggle('active',x===id));document.getElementById('title').textContent={chat:'AI Legal Counsel',case:'My Case',law:'Kansas Law',pfa:'PFA Analyzer',docs:'Evidence & Documents',timeline:'Case Timeline',attorney:'Attorney Handoff',forms:'Kansas Forms',deadlines:'Deadlines & Alerts'}[id];document.querySelectorAll('.nav').forEach((n,i)=>n.classList.toggle('active',false))}
function newCase(){view('case');document.getElementById('caseName').focus()}
function openSettings(){document.getElementById('settings').hidden=false}function closeSettings(){document.getElementById('settings').hidden=true}
function ask(q){document.getElementById('q').value=q;send()}
function addBubble(text,who='ai'){const d=document.createElement('div');d.className='bubble '+who;d.innerHTML=`<div class="avatar">${who==='ai'?'S':'U'}</div><div><b>${who==='ai'?'SlayLine':'You'}</b><p>${text}</p></div>`;document.getElementById('chatbox').appendChild(d);d.scrollIntoView({behavior:'smooth'})}
function answer(q){const x=q.toLowerCase();if(x.includes('pfa')&&(x.includes('hearing')||x.includes('standard')))return `<strong>Kansas PFA hearing:</strong> K.S.A. 60-3106 provides for a hearing within 21 days of filing. At the hearing, the plaintiff must prove the allegation of abuse by a preponderance of the evidence. The statute also addresses temporary orders pending the hearing and the parties' opportunity to present evidence.<br><br><span class="source">Authority: K.S.A. 60-3106 — verify the current text before relying on it.</span>`;if(x.includes('pfa')&&x.includes('order'))return `<strong>PFA orders:</strong> K.S.A. 60-3107 identifies multiple forms of relief, including restraints on abuse or interference with privacy/rights, residence provisions, temporary custody/residency and parenting time, support in specified circumstances, property provisions, counseling, and other acts necessary for safety. The signed order controls in an individual case.<br><br><span class="source">Authority: K.S.A. 60-3107.</span>`;if(x.includes('custody')||x.includes('parenting'))return `<strong>Kansas family-law scope:</strong> Chapter 23 includes legal custody, residency and parenting plans, parenting-time enforcement, child support, divorce, property division, spousal support and UCCJEA provisions. The production SlayLine retrieval engine should retrieve the exact statute and relevant Kansas appellate decisions for the facts presented.<br><br><span class="source">Authority: Kansas Family Law Code, Chapter 23.</span>`;return `I would research this in three layers: <strong>(1) controlling Kansas statute/court rule, (2) relevant Kansas appellate authority, and (3) the exact language in your court document.</strong> The production version must retrieve and verify those sources before giving a legal conclusion. It should never invent a citation.`}
async function send(){const box=document.getElementById('q'),q=box.value.trim();if(!q)return;addBubble(q,'user');box.value='';try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q})});const data=await r.json();let html=data.answer||'No answer returned.';if(data.authorities?.length){html+='<br><br><strong>Authorities</strong><ul>'+data.authorities.map(a=>`<li><a target="_blank" href="${a.url}">${a.citation} — ${a.title}</a></li>`).join('')+'</ul>'}if(data.uncertainty)html+=`<br><small>Uncertainty: ${data.uncertainty}</small>`;addBubble(html,'ai')}catch(e){addBubble(answer(q),'ai')}}
document.getElementById('q').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}})
function saveCase(){localStorage.setItem('slaylineCase',JSON.stringify({name:caseName.value,county:county.value}));alert('Case saved locally in this prototype. Production version uses encrypted server storage.')}
function fileAdded(input){if(input.files.length)alert('PFA uploaded in prototype. Production parser will OCR the order and extract every restriction, date and party.')}
function docsAdded(input){const list=document.getElementById('fileList');for(const f of input.files){const d=document.createElement('div');d.className='timelineitem';d.innerHTML=`<b>${f.name}</b><br><small>${Math.round(f.size/1024)} KB • awaiting production OCR/classification</small>`;list.appendChild(d)}document.getElementById('docCount').textContent=document.querySelectorAll('#fileList .timelineitem').length}
function addTimeline(){const d=document.getElementById('date').value,e=document.getElementById('event').value;if(!e)return;const x=document.createElement('div');x.className='timelineitem';x.innerHTML=`<b>${d||'Undated'}</b><br>${e}`;document.getElementById('timelineList').prepend(x);document.getElementById('event').value='';document.getElementById('eventCount').textContent=document.querySelectorAll('#timelineList .timelineitem').length}
